name: TheCavalry
favicon: null
layout_spectrum: 0.025945308385416865
typography_spectrum: 0.1485979100689292
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.19392051710747182
  lightness: 0.33495487412437797
  saturation: 0.5164503233972937
  rhythmicContrast: 0.16549963131546974
purpose: []
